config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "projects#index"
  resources :projects
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
    validates_presence_of :title, :description
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[ create edit update destroy ]
  
  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:title, :description)
    end
end

app/controllers/turbo_devise_controller.rb
class TurboDeviseController < ApplicationController
    class Responder < ActionController::Responder
        def to_turbo_stream
            controller.render(options.merge(formats: :html))
        rescue ActionView::MissingTemplate => error
            if get?
                raise error
            elsif has_errors? && default_action
                render rendering_options.merge(formats: :html, status: :unprocessable_entity)

            else
                redirect_to navigation_location
            end
        end
    end

    self.responder = Responder
    respond_to :html, :turbo_stream
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <title>Cs3300</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/jumbotron/">

  </head>

  <body>

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Portfolio</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <%= link_to "Home", root_path, class: "btn btn-success"  %> |
      <% if user_signed_in? %>
        <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-success" %> |
        <%= link_to "New Project", new_project_path, class: "btn btn-success" %> 
      <% else %>
        <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-success"  %> |
        <%= link_to "Sign In", new_user_session_path, class: "btn btn-success"  %> |
      <% end %>
    </div>
  </div>
</nav>
  

  <div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </div>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project, id: "epic-form") do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block"  %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="actions">
    <button type="submit" class="btn btn-dark"> Submit</button>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p>
    <strong>Title:</strong>
    <%= project.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= project.description %>
  </p>

</div>

app/views/projects/edit.html.erb
<div class="jumbotron">
  <div class="container p-5 my-5 bg-success text-white rounded border border-2 border-dark">
    <h1 class="display-3">  Editing Project  </h1>
    <%= render "form", project: @project %>
    <div>
      <%= link_to "Show this project", @project, class: "btn btn-dark" %> 
    </div>
  </div>
</div>

app/views/projects/index.html.erb
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/jumbotron/">

  </head>

<body>

<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
  <div class="container p-5 my-5 bg-success text-white border border-2 border-dark rounded">
    <h1 class="display-3">About this site</h1>
    <p>Developed by Hayley Jaap for CS3300: Intro to Software Engineering, this site functions as a portfolio for me to display my projects. </p>
  </div>
</div>

<div class="container">
  <!-- Example row of columns -->
  <h2 class="display-3 text-center">Projects</h2>
  <div class="card-deck">
    <div class="row">
      <% @projects.each do |project|  %>
        <div class="col-md-4">
          <div class="card p-3 bg-success text-white border border-2 border-dark" style="width: 25rem; height: 15rem;">
            <div class="card-body">
              <h4 class="card-title"> <%= project.title %> </h4>
              <p class="card-text"> <%= project.description %> </p>
              <h4 class="card-footer"> <%= link_to "Show this project", project, class: "btn btn-dark" %> </h4>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div> 
<!-- /container -->

</body>

app/views/projects/new.html.erb
<div class="jumbotron">
  <div class="container p-5 my-5 bg-success text-white rounded border border-2 border-dark">
    <h1 class="display-3">  New project  </h1>
    <%= render "form", project: @project %>
  </div>
</div>

app/views/projects/show.html.erb
<div class="jumbotron">
  <div class="container p-5 my-5 bg-success text-white rounded border border-2 border-dark">
    <h1 class="display-3"> <%= @project.title %> </h1>
    <p>
      <%= @project.description %>
    </p>
    <div class="btn-group">
      <%= link_to "Back to projects", root_path, class: "btn btn-dark" %>
      <% if user_signed_in? %>
        <%= link_to "Edit this project", edit_project_path(@project), class: "btn btn-dark" %>
        <%= button_to "Destroy this project", @project, method: :delete, class: "btn btn-dark" %>
      <% end %>
    </div>
  </div>
</div>